### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by dbof10** [SeriousAlexej/Ivo#4]
Thanks for open sourcing it. I'm really interested in the project. But I'm not from Qt world. Would you mind leaving a note how to build it on MacOS?

**Comment by SeriousAlexej** [comment]
Hey, thanks for taking interest in this project, even though it does not have any readme and such (wip).
I do not have access to MacOS and can not provide exact build instructions, but Ivo has only a few dependencies:

First, you will have to install **Qt**, from official website or maybe from a repository of some kind.
Next you will need to build\download **assimp** library. There's a good chance of it also already being available on some repository, maybe even at 'brew'.
The last one is **glm** library, it does not require any build steps and probably is also already available at brew.

I can not guarantee the build will succeed, because I have not tested my CMakeLists config on Mac, but if problems arise, they should be minimal. I tried to avoid platform-dependent code, so from source perspective everything has to be fine. Another potential issue is that Ivo uses deprecated version of OpenGL, but I would not worry about that.

**[.appveyor.yml](https://github.com/SeriousAlexej/Ivo/blob/master/.appveyor.yml)** and **[.travis.yml](https://github.com/SeriousAlexej/Ivo/blob/master/.travis.yml)** configs should also be helpful, they contain automated build instructions for Windows and Linux platforms respectively.

Project is still WIP and is worked on in spare time, so bugs may arise, but basic functionality is present and it is usable for small models. The viewports navigation might be tricky, but for 2D it is pretty standard. As for 3D, you can press _Esc_ key and use fps-like WASD + Space + C controls to fly over the scene.

**Comment by dbof10** [comment]
Could you provide some screenshot? and Which IDE, platform are you using to develop?

**Comment by SeriousAlexej** [comment]
I develop on Windows and Linux in QtCreator, but an IDE is not required to build the project. You only need a CMake and a working C++ compiler. Commands, required for build, are few, so there is not much to show on screenshots.
After installing dependencies and libraries, you only have to execute this command (this is from .appveyor.yml)
`cmake -Dassimp_ROOT="path_to_assimp" -Dglm_ROOT="path_to_glm"`
Moreover, if you install assimp and glm development libraries from repositories and not compile them yourself, you do not have to provide paths to them, so the command simplifies even more (from .travis.yml):
`cmake`
After that, you can call the build command:
`cmake --build .`

**Comment by dbof10** [comment]
Thank you for your response. Would you mind explaining how do you transform a 3D model to a papercraft. It would be helpful for me to understand the project

**Comment by SeriousAlexej** [comment]
I do not think Issues is the right place for it, but in a nutshell, 3D model is split into individual triangles, then each triangle is transformed to a 2D plane, and then triangles are joined back to form parts. Triangle can be attached to part if it does not overlap with it's geometry.

As for the issue itself, I will consider it closed as required build instructions are provided.

**Comment by dbof10** [comment]
yes, it should be closed. Can we have a channel to talk?

**Comment by SeriousAlexej** [comment]
seriousalexej@gmail.com
